In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [6]:
# 1. Create
[[1,2,3,4], [1,2,2,2]]
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [4]:
data

array([[[0.75595028, 0.73350628, 0.2873675 , 0.40537197],
        [0.81685647, 0.77691409, 0.69302066, 0.23186518],
        [0.01970868, 0.35599012, 0.70487906, 0.3548982 ]],

       [[0.36861351, 0.76501391, 0.38050099, 0.41073845],
        [0.00113145, 0.94911985, 0.36506789, 0.9784101 ],
        [0.52731651, 0.58504404, 0.8571134 , 0.79616947]]])

In [7]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [9]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [12]:
arr = np.array(([1,2,3,4],[1,2,3,4]))
type(arr)

numpy.ndarray

In [13]:
# attributes
shape = data.shape
size = data.size
types = data.dtype

In [16]:
types

dtype('float64')

In [17]:
# Slicing
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singlevel = data[0][0][0]
# single value retrieval

In [18]:
arr

array([[0.64649603, 0.76270097, 0.13518244, 0.03340586],
       [0.19006285, 0.13776639, 0.18744359, 0.78661277],
       [0.31739924, 0.10160074, 0.38835621, 0.76404917]])

In [19]:
singlevel

0.6464960333662155

In [20]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [21]:
list2

array([0.08160637, 0.14451384, 0.21652088, 0.22140048, 0.4969074 ,
       0.27092724, 0.17832729, 0.83785946, 0.25927989, 0.20780613])

In [22]:
# Basic math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)
# multiplies every item together

In [23]:
# Stat Functions - SAPLEMM
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [24]:
# ab = absolute values
# log = log function
# exp = exponential
# In summary, numpy.power is used for element-wise exponentiation with different exponents, while numpy.exp calculates the exponential function for each element in the input array

In [25]:
data.sort()

In [26]:
print(data.shape)

(2, 3, 4)


In [27]:
# I don't understand reshape!!!

In [28]:
zeroes = np.insert(zeros, 2, 1)
# array name, position, value to insert

In [29]:
data

array([[[0.03340586, 0.13518244, 0.64649603, 0.76270097],
        [0.13776639, 0.18744359, 0.19006285, 0.78661277],
        [0.10160074, 0.31739924, 0.38835621, 0.76404917]],

       [[0.49034898, 0.55590788, 0.66548116, 0.76531626],
        [0.10416515, 0.58613727, 0.75561963, 0.93362362],
        [0.04032466, 0.64625026, 0.66354891, 0.89144282]]])

In [30]:
np.delete(data, 0, axis=1)

array([[[0.13776639, 0.18744359, 0.19006285, 0.78661277],
        [0.10160074, 0.31739924, 0.38835621, 0.76404917]],

       [[0.10416515, 0.58613727, 0.75561963, 0.93362362],
        [0.04032466, 0.64625026, 0.66354891, 0.89144282]]])

In [31]:
# to save arrays

In [32]:
np.save("new array", data)

In [33]:
test = np.load("new array.npy")
test

array([[[0.03340586, 0.13518244, 0.64649603, 0.76270097],
        [0.13776639, 0.18744359, 0.19006285, 0.78661277],
        [0.10160074, 0.31739924, 0.38835621, 0.76404917]],

       [[0.49034898, 0.55590788, 0.66548116, 0.76531626],
        [0.10416515, 0.58613727, 0.75561963, 0.93362362],
        [0.04032466, 0.64625026, 0.66354891, 0.89144282]]])

In [34]:
# 3.4 4. Multidimensional Arrays

In [35]:
# Creating a simple array
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [36]:
# arrays do not have commas like lists do, once created
# ^^ this is a 1-dimensional array

In [37]:
# Different Size Dimensions

In [38]:
# Zero Dimensional Array
zero_dim = np.array(382759138)

In [39]:
print(zero_dim)

382759138


In [40]:
# One Dimensional Array
one_dim = np.array([1, 2, 3])
print(one_dim)

[1 2 3]


In [41]:
# Two Dimensional Array
two_dim = np.array([[1, 2, 3], [4, 5, 6]])
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [45]:
# Three Dimensional Array
three_dim = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(three_dim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [46]:
# Finding the dimension of a given array
print(three_dim.ndim) # this prints the dimension of a given array

3


In [47]:
# Given an array any dimension you want
new_array = np.array(17, ndmin=5)
print(new_array)

[[[[[17]]]]]


In [48]:
# INDEXING ARRAYS: https://www.youtube.com/watch?v=4n5dXRY2V7w

In [49]:
array = np.array([1, 2, 3, 4, 5]) # one dimensional array
print(array[0])

1


In [50]:
print(array[1]) 

2


In [52]:
# Two Dimensional Indexing
two_dim = np.array([[1, 2, 3], [4, 5, 6]])

In [53]:
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [54]:
print(two_dim[0])

[1 2 3]


In [55]:
print(two_dim[0,0]) # option 1

1


In [56]:
print(two_dim[0][0]) # option 2

1


In [57]:
# Three Dimensional Indexing
three_dim = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [58]:
print(three_dim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [59]:
print(three_dim[0, 1, 2])
# The first number corresponds to the first dimension and in the first dimension we have [[ 1  2  3]
  [ 4  5  6]]
    # The second number corresponds to the second dimension, in which the second element is:   [ 4  5  6]

IndentationError: unexpected indent (189712950.py, line 3)

In [60]:
# The third number (2) corresponds to the third dimension in which the third element is 6.

In [62]:
print(three_dim[0, 1, 2])

6
